language: node_js
node_js:
        - "12"
services:
        - docker

before_install:
        - npm install

script:
        - npm run nbuild
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t mrrs/mrrs-hello_docker .
        - docker push mrrs/mrrs-hello_docker
